// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb3XfAwz5TgnlQkx3dY3BbhLmmQhrgfkc',
    appId: '1:810684299054:web:3cfc0db9ed053bda01acbf',
    messagingSenderId: '810684299054',
    projectId: 'arenahub-ee4b0',
    authDomain: 'arenahub-ee4b0.firebaseapp.com',
    storageBucket: 'arenahub-ee4b0.firebasestorage.app',
    measurementId: 'G-91C2V4E8T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HEazBiWSHzI23_NgobsIrX_SJ0AEsSI',
    appId: '1:810684299054:android:ed51ce7420f759c401acbf',
    messagingSenderId: '810684299054',
    projectId: 'arenahub-ee4b0',
    storageBucket: 'arenahub-ee4b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNGZEigkvtH2B6My2paA2CGHUE8UrJBH8',
    appId: '1:810684299054:ios:f85a085cbeb74c0101acbf',
    messagingSenderId: '810684299054',
    projectId: 'arenahub-ee4b0',
    storageBucket: 'arenahub-ee4b0.firebasestorage.app',
    iosClientId: '810684299054-bgtvpe841v5pidda6ahasue80pkjqrl4.apps.googleusercontent.com',
    iosBundleId: 'com.computacao.arenahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNGZEigkvtH2B6My2paA2CGHUE8UrJBH8',
    appId: '1:810684299054:ios:f85a085cbeb74c0101acbf',
    messagingSenderId: '810684299054',
    projectId: 'arenahub-ee4b0',
    storageBucket: 'arenahub-ee4b0.firebasestorage.app',
    iosClientId: '810684299054-bgtvpe841v5pidda6ahasue80pkjqrl4.apps.googleusercontent.com',
    iosBundleId: 'com.computacao.arenahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb3XfAwz5TgnlQkx3dY3BbhLmmQhrgfkc',
    appId: '1:810684299054:web:7f59a22c28a4fe4d01acbf',
    messagingSenderId: '810684299054',
    projectId: 'arenahub-ee4b0',
    authDomain: 'arenahub-ee4b0.firebaseapp.com',
    storageBucket: 'arenahub-ee4b0.firebasestorage.app',
    measurementId: 'G-XKSGVS31CN',
  );
}
